apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "api.fullname" . }}-es-deployment
  labels:
    app: {{ template "api.fullname" . }}-es-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "api.fullname" . }}-es-deployment
  template:
    metadata:
      labels:
        app: {{ template "api.fullname" . }}-es-deployment
    spec:
      containers:
        - name: es
          image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
            - containerPort: 9300
