apiVersion: v1
kind: Service
metadata:
  name: {{ template "api.fullname" . }}-es-service
spec:
  ports:
    - name: one
      port: 9200
      targetPort: 9200
    - name: two
      port: 9300
      targetPort: 9300
  selector:
    app: {{ template "api.fullname" . }}-es-deployment
